objects/Guest__c.object
<CustomObject>
    <description>Data about visitor in hotel.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Card__c</fullName>
        <externalId>true</externalId>
        <label>ID Card</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <displayFormat>GN-{00000000}</displayFormat>
        <label>Guest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hotel__c.object
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Registered_Guest__c.object
<CustomObject>
    <description>Guest assigned to reservation and room that they are located in.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Guest__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guest</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Guest__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registered Guest</label>
    <nameField>
        <displayFormat>RG-{00000000}</displayFormat>
        <label>Registered Guest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registered Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>All informations about reserved rooms and associated guests.</description>
    <fields>
        <fullName>Reservation_Begin__c</fullName>
        <label>Reservation Begin</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reservation_End__c</fullName>
        <label>Reservation End</label>
        <type>DateTime</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reserved_Room__c.object
<CustomObject>
    <description>Connection between reservation and room.</description>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reserved Room</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Reserved Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reserved Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Data about room properties and it&apos;s binding to a certain hotel.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReceptionDeskControllerTest.cls
/**
 * Created by Mateusz on 2018-07-25.
 */

@IsTest
private class ReceptionDeskControllerTest {
    static testMethod void testFulfillingIfNewGuests() {
        Datetime dateBegin = Datetime.now();
        Datetime dateEnd = Datetime.now().addDays(5);

        Reservation__c reservation = new Reservation__c(Reservation_Begin__c=dateBegin, Reservation_End__c=dateEnd);
        insert reservation;
        Reservation__c testReservation = new Reservation__c(Reservation_Begin__c=dateBegin, Reservation_End__c=dateEnd);
        insert testReservation;

        Hotel__c hotel = new Hotel__c(Name='Test Hotel');
        insert hotel;

        Room__c room = new Room__c(Name='1', Hotel__c=hotel.Id, Capacity__c='2');
        insert room;
        Room__c testRoom = new Room__c(Name='2', Hotel__c=hotel.Id, Capacity__c='2');
        insert testRoom;

        Reserved_Room__c reservedRoom = new Reserved_Room__c(Reservation__c=reservation.Id, Room__c=room.Id);
        insert reservedRoom;

        Reserved_Room__c testReservedRoom = new Reserved_Room__c(Reservation__c=testReservation.Id, Room__c=testRoom.Id);
        insert testReservedRoom;

        List<Guest__c> guests = new List<Guest__c> {
                new Guest__c(First_Name__c='John', Last_Name__c='Tester', ID_Card__c='YPO564880'),
                new Guest__c(First_Name__c='Huablo', Last_Name__c='Tester', ID_Card__c='JQP723896')
        };

        List<Guest__c> testGuests = new List<Guest__c> {
                new Guest__c(First_Name__c='Maria', Last_Name__c='Tester', ID_Card__c='YPO564882'),
                new Guest__c(First_Name__c='Kaleb', Last_Name__c='Tester', ID_Card__c='JQP723897')
        };

        upsert guests;

        List<Registered_Guest__c> registeredGuests = new List<Registered_Guest__c> {
                new Registered_Guest__c(Guest__c=guests[0].Id, Reservation__c=reservation.Id),
                new Registered_Guest__c(Guest__c=guests[1].Id, Reservation__c=reservation.Id)
        };

        insert registeredGuests;

        List<Registered_Guest__c> testRegisteredGuests = new List<Registered_Guest__c> {
                new Registered_Guest__c(Reservation__c=testReservation.Id),
                new Registered_Guest__c(Reservation__c=reservation.Id)
        };

        List<String> reservationInfo = new List<String> {reservation.Id, reservation.Name};

        Test.startTest();
        List<String> expected = ReceptionDeskController.fulfillReservation(testGuests, testRegisteredGuests);
        Test.stopTest();

        System.assertEquals(reservationInfo.size(), expected.size(), 'Not equal :/');
    }
}