objects/Guest__c.object
<CustomObject>
    <description>Data about visitor in hotel.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Card__c</fullName>
        <externalId>true</externalId>
        <label>ID Card</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <displayFormat>GN-{00000000}</displayFormat>
        <label>Guest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hotel__c.object
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Registered_Guest__c.object
<CustomObject>
    <description>Guest assigned to reservation and room that they are located in.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Guest__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guest</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Guest__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registered Guest</label>
    <nameField>
        <displayFormat>RG-{00000000}</displayFormat>
        <label>Registered Guest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registered Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>All informations about reserved rooms and associated guests.</description>
    <fields>
        <fullName>Reservation_Begin__c</fullName>
        <label>Reservation Begin</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reservation_End__c</fullName>
        <label>Reservation End</label>
        <type>DateTime</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reserved_Room__c.object
<CustomObject>
    <description>Connection between reservation and room.</description>
    <fields>
        <fullName>Date_Begin__c</fullName>
        <formula>Reservation__r.Reservation_Begin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Begin</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_End__c</fullName>
        <formula>Reservation__r.Reservation_End__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reserved Room</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Reserved Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reserved Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Data about room properties and it&apos;s binding to a certain hotel.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_per_Day__c</fullName>
        <label>Price per Day</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReceptionDeskController.cls
/**
 * Created by Mateusz on 2018-07-17.
 */

public with sharing class ReceptionDeskController {
    @AuraEnabled
    public static List<Room__c> getAvailableRooms(Map<String, String> data, List<String> ignoredRooms) {
        List<Id> reservedRooms = new List<Id>();

        Datetime beginDate = (Datetime) JSON.deserialize('"'+data.get('begin')+'"', Datetime.class);
        Datetime endDate = (Datetime) JSON.deserialize('"'+data.get('end')+'"', Datetime.class);
        String capacity = data.get('capacity');

        List<Reserved_Room__c> reservationList = [SELECT Room__c
                FROM Reserved_Room__c
                WHERE Date_End__c > :beginDate
                AND Date_Begin__c < :endDate AND Room__r.Capacity__c = :capacity
                ];

        for (Reserved_Room__c item : reservationList) {
            reservedRooms.add(item.Room__c);
        }

        for (String roomId : ignoredRooms) {
            roomId = (Id) roomId;
            reservedRooms.add(roomId);
        }

        List<Room__c> foundRooms = [SELECT Name, Capacity__c, Price_per_Day__c, Hotel__r.Name
        FROM Room__c
        WHERE Id NOT IN :reservedRooms
        AND Capacity__c = :capacity
        ORDER BY Name ASC];

        if (foundRooms.size() > 0) {
            return foundRooms;
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static Id temporallyBlockRooms(List<Room__c> roomsToReserve, Map<String, String> dates) {
        List<Reserved_Room__c> reservedRooms = new List<Reserved_Room__c>();

        Datetime beginDate = (Datetime) JSON.deserialize('"'+dates.get('begin')+'"', Datetime.class);
        Datetime endDate = (Datetime) JSON.deserialize('"'+dates.get('end')+'"', Datetime.class);

        Reservation__c reservation = new Reservation__c(Reservation_Begin__c=beginDate, Reservation_End__c=endDate);

        insert reservation;

        for (Room__c room : roomsToReserve) {
            Reserved_Room__c tempReservedRoom = new Reserved_Room__c(Room__c=room.Id, Reservation__c=reservation.Id);
            reservedRooms.add(tempReservedRoom);
        }

        insert reservedRooms;

        return reservation.Id;
    }

    @AuraEnabled
    public static String[] fulfillReservation(Guest__c[] guests, Registered_Guest__c[] registeredGuests) {

        for (Guest__c guest : guests) {
            upsert guest ID_Card__c;
        }

        for (Integer i=0; i<registeredGuests.size(); i++) {
            registeredGuests[i].Guest__c = guests[i].Id;
        }

        insert registeredGuests;

        Reservation__c reservation = [SELECT Id, Name FROM Reservation__c WHERE Id = :registeredGuests[0].Reservation__c];
        List<String> reservationInfo = new List<String> {reservation.Id, reservation.Name};

        return reservationInfo;
    }

    @AuraEnabled
    public static void cancelReservation(String reservationId) {
        Reservation__c reservationToDelete = [SELECT Id FROM Reservation__c WHERE Id= :reservationId];
        delete reservationToDelete;
    }

    @AuraEnabled
    public static Guest__c getGuestByIDCard(String IDCard) {
        Guest__c foundGuest = [SELECT Id, First_Name__c, Last_Name__c, ID_Card__c FROM Guest__c WHERE ID_Card__c= :IDCard LIMIT 1];
        if (foundGuest.Id != null){
            return foundGuest;
        } else {
            return null;
        }
    }
}