objects/Hotel__c.object
<CustomObject>
    <fields>
        <fullName>Hotel_Picture_Path__c</fullName>
        <label>Hotel Picture Path</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AttachmentController.cls
/**
 * Created by Mateusz on 2018-07-26.
 */

public with sharing class AttachmentController {
    @AuraEnabled
    public static void updatePicturePath(String recId) {
        ContentDocumentLink docLink = [SELECT ContentDocumentId
                                FROM ContentDocumentLink
                                WHERE LinkedEntityId = :recId ORDER BY Id DESC LIMIT 1];

        ContentVersion ver = [SELECT Id
                            FROM ContentVersion
                            WHERE ContentDocumentId = :docLink.ContentDocumentId];
//
//        Hotel__c hotel = [SELECT Id FROM Hotel__c WHERE Id = :recId];
//        hotel.Hotel_Picture_Path__c = '/sfc/servlet.shepherd/version/download/'+ ver.Id;
//        upsert hotel;
    }
}