objects/Registered_Guest__c.object
<CustomObject>
    <description>Guest assigned to reservation and room that they are located in.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Guest__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Guest__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Registered Guests</relationshipLabel>
        <relationshipName>Registered_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registered Guest</label>
    <nameField>
        <displayFormat>RG-{00000000}</displayFormat>
        <label>Registered Guest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registered Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>All informations about reserved rooms and associated guests.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reserved_Room__c.object
<CustomObject>
    <description>Connection between reservation and room.</description>
    <fields>
        <fullName>Hotel_Name__c</fullName>
        <formula>Room__r.Hotel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hotel Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room_Number__c</fullName>
        <formula>Room__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Room Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reserved Rooms</relationshipLabel>
        <relationshipName>Reserved_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reserved Room</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Reserved Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reserved Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Data about room properties and it&apos;s binding to a certain hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReservationDataController.cls
/**
 * Created by Mateusz on 2018-07-20.
 */

public with sharing class ReservationDataController {
    @AuraEnabled
    public static Map<String, List<Object>> getReservationData(String reservationId) {
        List<Reserved_Room__c> reservedRooms = [SELECT Room__c, Room_Number__c, Hotel_Name__c
                                                FROM Reserved_Room__c
                                                WHERE Reservation__c = :reservationId];
        List<Registered_Guest__c> registeredGuests = [SELECT First_Name__c, Last_Name__c, Room__c
                                                FROM Registered_Guest__c
                                                WHERE Reservation__c = :reservationId];

        Map<String, List<Object>> reservationInfo = new Map<String, List<Object>>();

        reservationInfo.put('reservedRooms', reservedRooms);
        reservationInfo.put('registeredGuests', registeredGuests);

        return reservationInfo;
    }
}
//Map<String, List<Object>>